import { VIEW_CFG } from "/src/View/viewCfgEnum";

export const CONTROLLER_CFG = {
  MAX_DROP_INTERVAL: 2.2, // In seconds
  MIN_DROP_INTERVAL: 0.5, // In seconds

  STARTING_LIVES: 3,
  STARTING_SCORE: 0,
  SCORE_INCREASE_AMOUNT: 10,

  MILLISECONDS_IN_SECOND: 1000,

  PARACHUTIST_EVENT_DROWNED: VIEW_CFG.PARACHUTIST_EVENT_DROWNED,
  PARACHUTIST_EVENT_SAVED: VIEW_CFG.PARACHUTIST_EVENT_SAVED,

  LEFT_ARROW_KEY: 37,
  RIGHT_ARROW_KEY: 39
};
